@startuml
title Warm House Context Diagram

!include <C4/C4_Container>


Person(user, "User", "A user of the Warm House system")
System(accountManagement, "Account Management", "Registration of new accounts, settings")
System(deviceManagement, "Device Management", "Registration of new devices, settings, monitoring functions")
System(customScripts, "Custom Scripts", "Creation, Editing, Removal Scripts, customization of devices interaction")
System_Ext(partnerSystems, "Partner Systems", "Provides contracts for Devices")

Rel(user, accountManagement, "uses account")
Rel(user, customScripts, "manages scripts")
Rel(user, deviceManagement, "manages devices")
Rel(customScripts, accountManagement, "gets user metadata")
Rel(customScripts, deviceManagement, "makes integrations between devices")
Rel(deviceManagement, partnerSystems, "manages devices via external systems")

@enduml